name: Create PR from feature to develop

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        run: |
          gh pr create \
            --base develop \
            --head ${{ github.ref_name }} \
            --title "Auto PR: ${{ github.ref_name }} → develop" \
            --body "PR criado automaticamente."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}