name: "HOM DEPLOY"

on:
  push:
    branches:
      - hom

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: hom
    secrets:
      aws-assume-role-arn: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-statefile-s3-bucket: ${{ secrets.AWS_STATEFILE_S3_BUCKET }}
      aws-lock-dynamodb-table: ${{ secrets.AWS_LOCK_DYNAMODB_TABLE }}

  create-pr-to-prod:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if PR from hom to main exists
        id: check-pr
        run: |
          PR_EXISTS=$(gh pr list --head hom --base main --json number --jq 'length')
          echo "pr_exists=$PR_EXISTS" >> $GITHUB_OUTPUT
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Create PR from hom to main if not exists
        if: steps.check-pr.outputs.pr_exists == '0'
        run: |
          gh pr create --title "main <- hom" --body "Auto-generated PR after successful hom deployment" --head hom --base main
        env:
          TOKEN: ${{ secrets.TOKEN }}